server:
  port: 8001

spring:
  application:
    name: wiretransfer
  config:
    import: ${CONFIG_HOST:optional:configserver:http://localhost:8070/}
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}

transfer:
  url: ${BANK_HOST:http://localhost:8093/transactions}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

endpoints:
  shoutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8071/eureka/}

info:
  app:
    name: "wiretransfer"
    description: "Wire transfer system"
    version: "1.0.0"